[Show Originals] Update for React
new-xkit/XKit pull request #1988
Opened 2020-09-13 00:12 UTC by marcustyphoon

This updates Show Originals for the new dashboard. It uses the same collapse-post-to-an-indicator-with-a-show-button framework as #1956. (At present, this does not use/depend on an interface function for simplicity.)

See #1939 for development history. This is a subset of that PR's changes, others of which can be added in the future (i.e. the sidebar toggle).

2020-09-26 15:00 UTC, mtae commented
> It uses the same collapse-post-to-an-indicator-with-a-show-button framework as #1956.

Is there a toggle available as in No-Recommended? 

Also, is it possible to compare the blog url with the source url for reblogs to include self reblogs (and self-other-self reblogs etc)?

As opposed to reblogs where the blog it is reblogged on is different from the op of that post.

2020-09-27 05:23 UTC, marcustyphoon commented
> Is there a toggle available as in No-Recommended?

Yep!

> Also, is it possible to compare the blog url with the source url for reblogs to include self reblogs (and self-other-self reblogs etc)?
> As opposed to reblogs where the blog it is reblogged on is different from the op of that post.

I did implement this at an earlier point, but found it unnecessary for my use case when the included "show reblogs with added content" option is enabled. Given that that exists, do you still think you'd want it?

2020-09-28 01:13 UTC, mtae commented
That's even better! I didn't realize I wanted that but it's actually exactly the tumblr experience I'd like to have.

2021-03-31 22:59 UTC, marcustyphoon commented
Note for anyone that comes across this that this feature is implemented in [XKit Rewritten](https://github.com/AprilSylph/XKit-Rewritten)!

2021-05-10 02:30 UTC, hobinjk requested changes
Tested locally and LGTM. One minor fix inline. Thank you for your patience!

2021-05-10 02:30 UTC, hobinjk commented on Extensions/xkit_patches.js
> +					$(`.xkit-collapsed`).removeClass(`xkit-collapsed`);
Okay so realistically no recommended and show originals are unlikely to overlap their uninstall/teardown processes so all of this is fake and doesn't matter but I think this logic is a bit better as the following:
```javascript
$(`.${id}-collapsed`).removeClass(`xkit-collapsed`);
$(`.${id}-collapsed`).removeClass(`${id}-collapsed`);
```
As currently written if show originals calls destroy_collapsed it'll put no recommended's collapsed posts into a weird state.

2023-07-30 13:05 UTC, closed without merging